### ISSUE TITLE
Missing explenation on CoVariants server

### ISSUE THREAD

**Issue by kreativnix** [emmahodcroft/emmahodcroft.github.io#2]
Hi Emma,

sorry to post my question here but I don't know another possibility.

On the 21K Omicron  web page ( https://covariants.org/variants/21K.Omicron) I found a 
graph for the distribution per country and frequencies (in per cents) but I could not
understand what are the "100 %". All sequenced cases in a country or the sum of all cases?

For me it seems not to be that 100 % of a the cases in South Korea are based on Omicron.
Also 7 % for Austria would be too much as far as I know.

Could you please explain that to me?

Best regards
Gerald

**Comment by emmahodcroft** [comment]
Hi @kreativnix ! No problem at all. I'm sorry you couldn't find the explanation for the Per Country graphs very easily - it's actually up at the top of the P[er Country page](https://covariants.org/per-country) 😄 
The graphs are for all the sequences from a country, not cases - which is very important to keep in mind, as you point out - because the sequences may differ from cases, and particularly with new variants, sequences from that variant may be preferentially searched for, selected for sequencing, and be sequenced faster, which can skew results. There are some other notes on how to interpret the graphs with caution at the top of the page, too!

**Comment by kreativnix** [comment]
Hi!
Many thanks for your quick answer. The link helped me a lot!.
Best regards
Gerald
